export const LANGUAGES = [
  {
    id: "en",
    name: "English",
    flag: "https://hatscripts.github.io/circle-flags/flags/us.svg",
    subdomain: "en",
  },
  {
    id: "de",
    name: "Deutsch",
    flag: "https://hatscripts.github.io/circle-flags/flags/de.svg",
    subdomain: "de",
  },
  {
    id: "fr",
    name: "Français",
    flag: "https://hatscripts.github.io/circle-flags/flags/fr.svg",
    subdomain: "fr",
  },
  {
    id: "es",
    name: "Español",
    flag: "https://hatscripts.github.io/circle-flags/flags/es.svg",
    subdomain: "es",
  },
  {
    id: "it",
    name: "Italiano",
    flag: "https://hatscripts.github.io/circle-flags/flags/it.svg",
    subdomain: "it",
  },
  {
    id: "pt",
    name: "Português",
    flag: "https://hatscripts.github.io/circle-flags/flags/br.svg",
    subdomain: "pt",
  },
  {
    id: "ru",
    name: "Русский",
    flag: "https://hatscripts.github.io/circle-flags/flags/ru.svg",
    subdomain: "ru",
  },
  {
    id: "zh",
    name: "中文",
    flag: "https://hatscripts.github.io/circle-flags/flags/cn.svg",
    subdomain: "zh",
  },
  {
    id: "ja",
    name: "日本語",
    flag: "https://hatscripts.github.io/circle-flags/flags/jp.svg",
    subdomain: "ja",
  },
  {
    id: "ar",
    name: "العربية",
    flag: "https://hatscripts.github.io/circle-flags/flags/sa.svg",
    subdomain: "ar",
  },
  {
    id: "fa",
    name: "فارسی",
    flag: "https://hatscripts.github.io/circle-flags/flags/ir.svg",
    subdomain: "fa",
  },
  {
    id: "he",
    name: "עברית",
    flag: "https://hatscripts.github.io/circle-flags/flags/il.svg",
    subdomain: "he",
  },
  {
    id: "hi",
    name: "हिन्दी",
    flag: "https://hatscripts.github.io/circle-flags/flags/in.svg",
    subdomain: "hi",
  },
  {
    id: "eu",
    name: "Euskara",
    flag: "https://hatscripts.github.io/circle-flags/flags/es-pv.svg",
    subdomain: "eu",
  },
];